name: Playbook
configFiles:
  Debug: XCConfigs/project.xcconfig
  Release: XCConfigs/project.xcconfig
options:
  bundleIdPrefix: app.playbook-ui
  createIntermediateGroups: true

schemes:
  Playbook:
    build:
      targets:
        Playbook: all
        PlaybookUI: [test]
        PlaybookSnapshot: [test]
    test:
      targets:
        - Playbook-Tests
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/Snapshots

  PlaybookUI:
    build:
      targets:
        PlaybookUI: all

  PlaybookSnapshot:
    build:
      targets:
        PlaybookSnapshot: all
        
  PlaybookAccessibility:
    build:
      targets:
        PlaybookAccessibility: all
    test:
      targets:
        - Playbook-Accessibility-Tests
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR_ACC: $(SOURCE_ROOT)/AccessibilitySnapshots

targets:
  Playbook:
    type: framework
    platform: iOS
    sources:
      - Sources/Playbook
    configFiles:
      Debug: XCConfigs/playbook.xcconfig
      Release: XCConfigs/playbook.xcconfig

  PlaybookUI:
    type: framework
    platform: iOS
    sources:
      - Sources/PlaybookUI
    configFiles:
      Debug: XCConfigs/playbook-ui.xcconfig
      Release: XCConfigs/playbook-ui.xcconfig
    dependencies:
      - target: Playbook

  PlaybookSnapshot:
    type: framework
    platform: iOS
    sources:
      - Sources/PlaybookSnapshot
    configFiles:
      Debug: XCConfigs/playbook-snapshot.xcconfig
      Release: XCConfigs/playbook-snapshot.xcconfig
    dependencies:
      - target: Playbook

  PlaybookAccessibility:
    type: framework
    platform: iOS
    sources:
      - Sources/PlaybookAccessibility
    configFiles:
      Debug: XCConfigs/playbook-accessibility.xcconfig
      Release: XCConfigs/playbook-accessibility.xcconfig
    dependencies:
      - target: Playbook

  Playbook-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/Playbook
      - Tests/Support
    dependencies:
      - target: Playbook
      - target: PlaybookUI
      - target: PlaybookSnapshot
      
  Playbook-Accessibility-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/Accessibility
      - Tests/Support
    dependencies:
      - target: Playbook
      - target: PlaybookUI
      - target: PlaybookAccessibility
